fix: vue in edit grammars
getgrit/gritql pull request #11
Opened 2024-03-12 20:04 UTC by ilevyor

edit grammars didn't handle due

2024-03-12 20:11 UTC, morgante commented
> edit grammars didn't handle due

vue...?

2024-03-12 20:11 UTC, morgante commented on resources/edit_grammars.mjs
> +    // typescript is special
Is this about TypeScript or is it about Vue?

2024-03-12 20:12 UTC, morgante requested changes
Please self-review your own work. This is littered with typos and copy/paste.

2024-03-12 20:15 UTC, morgante approved these changes

2024-03-12 20:20 UTC, merged

2024-04-04 14:34 UTC, nicooprat commented
Any ETA when this will be released? Thanks 🙏

2024-04-04 17:02 UTC, morgante commented
Hi @nicooprat, this was in the last release so JavaScript patterns should now target Vue.